tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: eoi_ws
      schema: dev
      warehouse: COMPUTE_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: eoi_ws
      schema: prd
      warehouse: COMPUTE_WH